name: Build And Deploy
# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Deploy Website
                uses: garygrossgarten/github-action-scp@release
                with:
                    local: public
                    remote: public_html
                    host: server245.web-hosting.com
                    port: 21098
                    privateKey: ${{ secrets.NAMECHEAP_P_KEY }}
                    rmRemote: true
