name: Build And Deploy
# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Deploy Website
                uses: garygrossgarten/github-action-scp@release
                with:
                    local: test
                    remote: scp/directory
                    host: ${{ secrets.W1_HOST }}
                    privateKey: ${{ secrets.W1_KEY }}
                    rmRemote: true
